### ISSUE TITLE
Virus name reported as virus

### ISSUE THREAD

**Issue by ondrejj** [interserver/clamav-unofficial#1]
Looks like at least one specific virus name is reported as virus. To avoid filtering of this report, I will report virus name in next message (I am sorry).
After more investigation, it's enough a short part of this threat.

**Comment by ondrejj** [comment]
Here is how to reproduce:
```
echo wp-admin/5 > /tmp/test
clamscan /tmp/test
```

Results:

```
/tmp/test: sigs.InterServer.net.HEX.Topline.include.wp-admin/5.1094.UNOFFICIAL FOUND
```

To avoid similar problems in future, try to export all virus names and scan them before a release.

**Comment by JQuags** [comment]
Thanks for the report. This will be resolved the next time the virus db is updated.
