### ISSUE TITLE
Provide sha256 or md5 hashes of signature databases

### ISSUE THREAD

**Issue by Gazoo** [interserver/clamav-unofficial#2]
It would be good if sha256 or md5 hashes were generated for each database. That way any scripts can check if the hash has changed before actually downloading the file. This will cut down on bandwidth usage and any downloads can be verified.

Eg:
https://sigs.interserver.net/interserver256.hdb.sha256
https://sigs.interserver.net/interservertopline.db.sha256
https://sigs.interserver.net/shell.ldb.sha256

**Comment by JQuags** [comment]
I have added md5 at

https://github.com/interserver/clamav-unofficial/blob/master/interserver256.hdb.md5
https://github.com/interserver/clamav-unofficial/blob/master/interservertopline.db.md5
